homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  elevation: 11
  temperature_unit: C
  unit_system: metric
  time_zone: !secret TZ
  customize: !include customize.yaml
  customize_glob: !include customglobs.yaml

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  radius: 50
  icon: mdi:account-multiple

config:

sun:

zeroconf:

customizer:
  custom_ui: hosted

frontend:
  javascript_version: auto
  themes: !include_dir_merge_named extras/themes/
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-mini-media-player.html
    - /local/custom_ui/state-card-hline.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-mini-media-player_es5.html
    - /local/custom_ui/state-card-hline_es5.html

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 3

#ios:

homekit:
  auto_start: false
  filter:
    include_domains:
#      - sensor
      - switch
      - light
#    exclude_entities:
#      - group.weather_overview
#      - group.sysinfo

telegram_bot:
  - platform: polling
    api_key: !secret tgram_key
    parse_mode: html
    allowed_chat_ids:
      - !secret tgram_chatid

notify:
  - platform: telegram
    name: d
    chat_id: !secret tgram_chatid

weblink:
  entities:
    - name: Github
      url: !secret weblink_github
    - name: Router
      url: !secret weblink_router
    - name: Pi-hole
      url: !secret weblink_pihole

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: !secret mqtt_host
  port: 1883
  protocol: 3.1
  client_id: HA_bridge
  keepalive: 60
  username: pi
  password: !secret mqtt_key
  discovery: true
  discovery_prefix: HA

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

alert:
  maintenance_mode_alert:
    name: Maintenance Mode has been on for a long time
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - d

#image_processing:
#  - platform: dlib_face_detect
#    keep_images_without_faces: False
#    source:
#      - entity_id: camera.backdoor
#        name: "Detect"
#  - platform: dlib_face_identify
#    keep_known_faces: true
#    source:
#      - entity_id: camera.backdoor
#        name: "Identify"
#    faces:
#      D: /home/homeassistant/.homeassistant/www/Dface.jpg

#apple_tv:
#  - host: 192.168.0.106
#    login_id: !secret appletv_id
#    name: SS_Home
#    start_off: false
#    credentials:

###########        INCLUDES       ###########
shell_command: !include shellcmds.yaml
input_boolean: !include inputs/input_boolean.yaml
input_number: !include inputs/input_number.yaml
input_select: !include inputs/input_select.yaml
input_text: !include inputs/input_text.yaml
device_tracker: !include device_tracker.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include binary_sensor.yaml
switch: !include_dir_merge_list switches/
script: !include_dir_merge_named scripts/
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
camera: !include camera.yaml
light: !include_dir_merge_list lights/

discovery:

map:

recorder:
  purge_interval: 7
  purge_keep_days: 3
  db_url: sqlite:///home/homeassistant/.homeassistant/home-assistant_v2.db

history: !include extras/logger.yaml

logbook: !include extras/logger.yaml

logger:
#  default: info
   default: warning
#   logs:
#      homeassistant.components.homekit: debug

updater:
