#- platform: icloud
#  username: !secret d
#  password: !secret i
- platform: nmap_tracker
  hosts: 192.168.0.0/24
  exclude: 192.168.0.200

  track_new_devices: true
  home_interval: 5
  interval_seconds: 120
  consider_home: 0:08
