- platform: template
  sensors:
    dark_outside:
      value_template: >
        {% if (states.sun.sun.attributes.elevation|int < 3) %}true
        {% elif ((states.sun.sun.attributes.elevation|int < 4.5) and (states.sensor.pws_uv.state|int < 0)) %}true
        {% elif ((states.sun.sun.attributes.elevation|int < 6) and (states.sensor.pws_uv.state|int < 0)) %}true
        {% else %} false {% endif %}

#    bad_weather:
#      value_template: >
#        {% if states('sensor.pws_temp_c.state')|int > 38 %} heat_wave
#        {% elif ((states.sensor.sensor.pws_temp_c.state|int < 23) and (states.sensor.pws_precip_1d.state|int > 97)
#          and (states.sensor.pws_relative_humidity.state|int > 97)
#          and (states.sensor.pws_wind_kph.state|int > 25)) %} heavy_rain
#        {% else %} clear {% endif %}


# abs(elevation/10) * ( (elevation/10) + (1- (cloudiness/100)))

# where 10 - your local threshold for sunset.
