- platform: template
  sensors:
    home_status:
      friendly_name: 'Home status'
      value_template: >
        {% if is_state('group.presence' , 'home') %}Occupied
        {% else %} Unoccupied {% endif %}
