- platform: rest
  name: dns_queries_today
  resource: !secret pi_hole_url
  value_template: '{{ value_json.dns_queries_today }}'

- platform: rest
  name: domains_being_blocked
  resource: !secret pi_hole_url
  value_template: '{{ value_json.domains_being_blocked }}'

- platform: rest
  name: ads_blocked_today
  resource: !secret pi_hole_url
  value_template: '{{ value_json.ads_blocked_today }}'

- platform: rest
  name: ads_percentage_today
  resource: !secret pi_hole_url
  value_template: '{{ value_json.ads_percentage_today | int }}'

- platform: rest
  name: unique_domains
  resource: !secret pi_hole_url
  value_template: '{{ value_json.unique_domains }}'

- platform: rest
  name: queries_forwarded
  resource: !secret pi_hole_url
  value_template: '{{ value_json.queries_forwarded }}'

- platform: rest
  name: queries_cached
  resource: !secret pi_hole_url
  value_template: '{{ value_json.queries_cached }}'

######Custom Version sensor
- platform: command_line
  command: "pihole -v -p -c"
  name: 'pihole_version_current'
  value_template: '{{ value[28:] }}'
  scan_interval: 86400

- platform: command_line
  command: "pihole -v -p -l"
  name: 'pihole_version_latest'
  value_template: '{{ value[27:] }}'
  scan_interval: 86400

- platform: template
  sensors:
    pi_hole_version:
      value_template: "{%- if states.sensor.pihole_version_current.state == states.sensor.pihole_version_latest.state -%}{{states.sensor.pihole_version_current.state}} {% else %}{{states.sensor.pihole_version_latest.state}} Available{% endif%}"
      icon_template: >-
        {% if states.sensor.pihole_version_current.state == states.sensor.pihole_version_latest.state %}
          mdi:checkbox-marked
        {% else %}
          mdi:checkbox-blank-outline
        {% endif %}
###### I had to provide access in sudoers file for this script to run.
- platform: command_line
  command: 'pihole status'
  name: 'pihole_status_raw'
  scan_interval: 60

- platform: template
  sensors:
    pihole_dns:
      value_template: "{{states.sensor.pihole_status_raw.state.split('[✓]')[1][1:-3]}}"
      icon_template: >-
        {%- if states.sensor.pihole_status_raw.state.split('[✓]')[1][1:-3] == 'DNS service is running' -%}
          mdi:checkbox-marked
        {%- else -%}
          mdi:checkbox-blank-outline
        {%- endif -%}
- platform: template
  sensors:
    pihole_blocking:
      value_template: "{{states.sensor.pihole_status_raw.state.split('[✓]')[2][1:]}}"
      icon_template: >-
        {%- if states.sensor.pihole_blocking.state == 'Pi-hole blocking is Enabled' -%}
          mdi:checkbox-marked
        {%- else -%}
          mdi:checkbox-blank-outline
        {%- endif -%}
- platform: template
  sensors:
    pihole_status:
      value_template: >-
        {% if states.sensor.pihole_blocking.state == 'Pi-hole blocking is Enabled' %}
          True
        {% else %}
          False
        {% endif %}
