- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: ipv4_address
      arg: enxb827ebe7c1e9
    - type: network_in
      arg: enxb827ebe7c1e9
    - type: network_out
      arg: enxb827ebe7c1e9
