- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: ipv4_address
      arg: enxb827ebe7c1e9
    - type: network_in
      arg: enxb827ebe7c1e9
    - type: network_out
      arg: enxb827ebe7c1e9

- platform: rest
  resource: https://pypi.python.org/pypi/homeassistant/json
  name: HASS Version Upstream
  value_template: "{{ value_json.info.version }}"
  scan_interval: 3600

- platform: command_line
  name: HASS Version Installed
  command: "cat /home/homeassistant/.homeassistant/.HA_VERSION"
  value_template: '{{value}}'

- platform: template
  sensors:
    hass_version:
      value_template: "{%- if states.sensor.hass_version_upstream.state == states.sensor.hass_version_installed.state-%}{{states.sensor.hass_version_installed.state}} {% else %}{{states.sensor.hass_version_upstream.state}} Available{% endif%}"
      icon_template: >-
        {% if states.sensor.hass_version_upstream.state == states.sensor.hass_version_installed.state %}
          mdi:checkbox-marked
        {% else %}
          mdi:checkbox-blank-outline
        {% endif %}
