- platform: mqtt
  name: "Tele Temperature"
  state_topic: "tele/AC-01/SENSOR"
  value_template: "{{ value_json['DHT11'].Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Tele Humidity"
  state_topic: "tele/AC-01/SENSOR"
  value_template: "{{ value_json['DHT11'].Humidity }}"
  unit_of_measurement: "%"
