- alias: Shutdown Notification
  initial_state: 'on'
  id: '00'
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: ifttt.trigger
    data:
      event: Hass.io
      value1: '!!OFFLINE!!'
- alias: Startup Notification
  initial_state: 'on'
  id: '01'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: ifttt.trigger
    data:
      event: Hass.io
      value1: 'I am Up!'
