- alias: Flux Start
  initial_state: 'on'
  hide_entity: true
  id: '28'
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
        below: 20.0
      - condition: state
        entity_id: sensor.darkoutside
        state: 'true'
  action:
    - delay: 00:01
    - service: homeassistant.turn_on
      entity_id: switch.flux
- alias: Flux Stop
  initial_state: 'on'
  hide_entity: true
  id: '29'
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
        above: 10.0
      - condition: state
        entity_id: sensor.darkoutside
        state: 'false'
  action:
    - delay: 00:01
    - service: homeassistant.turn_off
      entity_id: switch.flux
