- alias: Flux Start
  initial_state: 'on'
  hide_entity: true
  id: '28'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
    # Can be a positive or negative number
      below: 45.0
    - platform: state
      entity_id: sensor.darkoutside
      to: 'true'
  condition:
    condition: state
    entity_id: switch.flux
    state: 'off'
  action:
    - delay: 00:01
    - service: homeassistant.turn_on
      entity_id: switch.flux
- alias: Flux Stop
  initial_state: 'on'
  hide_entity: true
  id: '29'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
    # Can be a positive or negative number
      above: 45.0
    - platform: state
      entity_id: sensor.darkoutside
      to: 'false'
  condition:
    condition: state
    entity_id: switch.flux
    state: 'on'
  action:
    - delay: 00:01
    - service: homeassistant.turn_off
      entity_id: switch.flux
