- alias: Occupancy - Return home
  initial_state: on
  hide_entity: true
  id: '12'
  trigger:
    platform: state
    entity_id: group.presence
    to: 'home'
  action:
    service: homeassistant.turn_off
    entity_id:
      - input_boolean.holiday_mode
      - input_boolean.away_mode

- alias: Occupancy - Nobody home
  initial_state: on
  hide_entity: true
  id: '13'
  trigger:
    platform: state
    entity_id: sensor.home_status
    to: 'Unoccupied'
    for:
      minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.away_mode
#        - script.empty_bedroom

- alias: Occupancy - Holiday Mode
  initial_state: on
  hide_entity: true
  id: '14'
  trigger:
    platform: state
    entity_id: input_boolean.away_mode
    to: 'on'
    for:
      hours: 24
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.holiday_mode
    - service: homeassistant.turn_off
      entity_id: input_boolean.away_mode

- alias: Occupancy - Trackable device detected
  initial_state: on
  hide_entity: true
  id: '15'
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: script.notify
    data:
      tell: d
      message: 'New trackable device detected'

- alias: Occupancy - Verify ios D
  initial_state: on
  hide_entity: true
  id: '16'
  trigger:
    platform: time
    minutes: '/30'
    seconds: 00
  condition:
    - condition: time
      after: '08:00:00'
      before: '23:00:00'
    - condition: template
      value_template:  "{{ as_timestamp(now()) - as_timestamp(states.device_tracker.dsiphone.last_updated) > (61*60) }}"
  action:
    service: notify.d
    data:
      message: "request_location_update"
