- alias: (Presence) G Home
  initial_state: 'on'
  hide_entity: true
  id: '06'
  trigger:
    platform: state
    entity_id: device_tracker.gaurisiphone
    to: 'home'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.G_status
      option: Home

- alias: (Presence) G Away
  initial_state: 'on'
  hide_entity: true
  id: '07'
  trigger:
    platform: state
    entity_id: device_tracker.gaurisiphone
    to: 'not_home'
    for:
      minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.G_status
        option: Away

- alias: (Presence) G Sleeping
  initial_state: 'on'
  hide_entity: true
  id: '08'
  trigger:
    platform: state
    entity_id: input_select.D_status
    to: 'Sleeping'
  action:
    service: script.notify
    data:
      tell: d
      no_say: 1
      call_goodnight: 1
