- alias: (Presence) D Home/Night
  initial_state: 'on'
  hide_entity: true
  id: '03'
  trigger:
    platform: state
    entity_id: device_tracker.dsiphone
    to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.D_status
        option: Home
    - condition: state
      entity_id: sensor.dark_outside
      state: 'true'
    - service: script.turn_on
      entity_id: script.fadelighton
- alias: (Presence) D Away
  initial_state: 'on'
  hide_entity: true
  id: '04'
  trigger:
    platform: state
    entity_id: device_tracker.dsiphone
    from: 'home'
    to: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.D_status
        option: Away
    - service: script.turn_off
      entity_id: script.fadelightoff
- alias: (Presence) D Sleeping
  initial_state: 'on'
  hide_entity: true
  id: '05'
  trigger:
    platform: state
    entity_id: input_select.D_status
    to: 'Sleeping'
  action:
    service: script.turn_on
    entity_id: script.nightlight
