- alias: (Presence) D Home/Night
  initial_state: 'on'
  hide_entity: true
  id: '03'
  trigger:
    platform: state
    entity_id: device_tracker.dsiphone
    to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.D_status
        option: Home

- alias: (Presence) D Away
  initial_state: 'on'
  hide_entity: true
  id: '04'
  trigger:
    platform: state
    entity_id: device_tracker.dsiphone
    to: 'not_home'
    for:
      minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.D_status
        option: Away

- alias: (Presence) D Sleeping
  initial_state: 'on'
  hide_entity: true
  id: '05'
  trigger:
    platform: state
    entity_id: input_select.D_status
    to: 'Sleeping'
  action:
    service: script.nightlight
