- alias: Lighting - ON (Halls/Night)
  initial_state: 'on'
  hide_entity: true
  id: '30'
  trigger:
    - platform: state
      entity_id: sensor.dark_outside
      to: 'true'
    - platform: time
      at: '18:30:00'
#  condition: state
#  entity_id: sensor.home_status
#  to: 'Occupied'
  action:
    - service: light.turn_on
      entity_id: group.hall_lights
#    - service: script.notify
#      data:
#        call_dark_outside: 1

- alias: Lighting - OFF (Home/Day)
  initial_state: 'on'
  hide_entity: true
  id: '31'
  trigger:
    - platform: state
      entity_id: sensor.dark_outsie
      to: 'false'
  action:
    - service: light.turn_off
      entity_id: group.hall_lights
#    - service: script.notify
#      data:
#        call_light_outside: 1

- alias: Lighting - OFF (Hall/Night)
  initial_state: 'on'
  hide_entity: true
  id: '37'
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: light.turn_off
      entity_id: light.display
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.bar
    - service: homeassistant.turn_off
      entity_id: group.hall_lights
