- alias: sunset
  initial_state: 'on'
  hide_entity: true
  id: '10'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    # Can be a positive or negative number
    below: 20.0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.dsiphone
        state: 'home'
      - condition: time
        before: '20:00:00'
      - condition: state
        entity_id: light.backlight
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.fadelighton
