- alias: Shutdown Notification
  initial_state: 'on'
  hide_entity: true
  id: '00'
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    service: ifttt.trigger
    data:
      event: Hass.io
      value1: '!!OFFLINE!!'

- alias: Startup Notification
  initial_state: 'on'
  hide_entity: true
  id: '01'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: ifttt.trigger
    data:
      event: Hass.io
      value1: 'I am Up!'

- alias: rD [PI] - Update Notification
  initial_state: 'off'
  hide_entity: true
  id: '32'
  trigger:
    platform: state
    entity_id: sensor.ha_upstream
  action:
    - delay: '00:30:00'
    - service: script.notify
      data:
        no_say: 1
        tell: d
        call_upgrade: 1

- alias: Device - Disk use alarm
  initial_state: 'off'
  hide_entity: true
  id: '33'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent_
    above: 85
  action:
    service: script.notify
    data:
      tell: d
      no_say: 1
      call_hdd_space: 1

- alias: Device - System load alarm
  initial_state: 'off'
  hide_entity: true
  id: '34'
  trigger:
    - platform: numeric_state
      entity_id: sensor.processor_use
      above: 85
    - platform: numeric_state
      entity_id: sensor.memory_use_percent
      above: 85
  action:
    service: script.notify
    data:
      tell: d
      no_say: 1
      call_system_load: 1

- alias: Device - Power on
  initial_state: 'off'
  hide_entity: true
  id: '35'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: script.notify
    data:
      call_power_on: 1
      tell: d
